#	  _____       _ _ _                 _     
#	 / ____|     (_) | |               | |  _ 
#	| (___   __ _ _| | |__   ___   __ _| |_(_)
#	 \___ \ / _` | | | '_ \ / _ \ / _` | __|  
#	 ____) | (_| | | | |_) | (_) | (_| | |_ _ 
#	|_____/ \__,_|_|_|_.__/ \___/ \__,_|\__(_)
                                          
# Basic Setup:
name = "Tiller"
short_name = "tiller"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = "A small example sailboat plugin."
description = ""
url = "https://github.com/cole-wilson/tiller"
keywords = ""
license = "none"
latest_build = "0.1.0"
release-notes = "init2"
latest_release = "0.0.2"


# Resource Setup:
[resources]
icon = ""
data_files = []
modules = [ "sailboat",]
file = "main.py"
no_import = []


# Plugin Commands:
[command.tiller]
string = "dasfsdkfghjhksdgfhjkdsgfjhsgf"


# Build Routines:
[build.pyinstaller]
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.colewilson.tiller"

[build.pypi.commands]
rudder = "__main__.command"

[build.pypi.entry_points.sailboat_plugins]
tiller = "tiller.__main__:Tiller"


# Release Routines:
[release.github_release]


# Other:
[git]
github = "cole-wilson/tiller"


# Thank you for using Sailboat!